### ISSUE TITLE
Compatability Issue

### ISSUE THREAD

**Issue by idkwhattotype019238** [DakotaPride/create-garnished#15]
im having a compatability issue where the heat from the blaze burner combined with the water and sugar try to make caramel from create confectionery when im trying to make liquid garnish and it also conflicts with create cafe's melted sugar so i can only make liquid garnish by random chance and not be able to mass produce liquid garnish or it will either randomly make caramel or melted sugar

**Comment by DakotaPride** [comment]
Hello! Thank you for bringing this to my attention! However, considering that filters can help prevent this, the recipe will most likely not change. If you believe that there is another way that this issue can be solved, feel free to let me know and I'll see what I can do!

**Comment by idkwhattotype019238** [comment]
Hello, sorry if I'm taking time off of developing this mod, but I've tried using filters and they don't affect the output of the recipe and the only way I got it to work was when I put 250 mb of water and one of each ingredient, my suggestion on how to solve the issue is to make the recipe use crushed salt instead of sugar, it would remove compatibility issues and won't really affect progression, the only other thing you would need would be a millstone.

**Comment by DakotaPride** [comment]
Don't worry! Currently, most (if not all) content-related features are complete and I am just fine-tuning and fixing some last-minute tweaks and bugs, as well as working on the next update coming after v0.9. This isn't a terrible idea, as you mentioned, it wouldn't really change progression that much. Thank you, I will take this suggestion into consideration while finishing up the update!

**Comment by DakotaPride** [comment]
Apologies, but are you on Fabric or Forge and what MC version are you playing on? Testing using a "List Filter" and setting the liquid to use a bucket variant allows filtered mixing just fine on a Forge 1.19.2 instance.

**Comment by idkwhattotype019238** [comment]
I am using forge 1.19.2  I'm currently trying to use the list filter and when I do it just blocks the recipe from working I will try to send a video of it on the discord I am also using garnished v 0.8 and create 0.5.1c

**Comment by DakotaPride** [comment]
If you have JEI installed, drag the Bucket of Garnish into the List Filter and it should work. I've also messaged you on Discord regarding the placement of posts.

**Comment by idkwhattotype019238** [comment]
You're right but it would still be nice to not have to use a filter to mass produce liquid garnish.
