### ISSUE TITLE
Not compatible with Create 0.5.1e

### ISSUE THREAD

**Issue by Amronos** [DakotaPride/create-garnished#17]
Minecraft Version: 1.20.1
Forge Version: 47.2.1

[debug.log](https://github.com/DakotaPride/create-garnished/files/12774431/debug.log)
[latest.log](https://github.com/DakotaPride/create-garnished/files/12774432/latest.log)
[crash-2023-09-30_15.59.40-fml.txt](https://github.com/DakotaPride/create-garnished/files/12774433/crash-2023-09-30_15.59.40-fml.txt)

**Comment by DakotaPride** [comment]
I'm sorry, but no official support will be provided until this version is available for Fabric. I highly suggest downgrading Create to 0.5.1d or under to solve this issue. If the problem persists, feel free to let me know!

**Comment by DakotaPride** [comment]
It should FINALLY be fixed, if you do still experience issues, feel free to let me know!
