### ISSUE TITLE
Cashew and Almond trees bugged

### ISSUE THREAD

**Issue by myriantics** [DakotaPride/create-garnished#18]
When you grow a Cashew tree or an Almond tree, the block below the tree is deleted.

Fabric version 0.14.22
MC version 1.20
Create 0.5.1-d
Garnished 0.8

**Comment by DakotaPride** [comment]
Thank you for bringing this to my attention! This issue should be fixed upon the release of v0.9, thank you for your understanding and patience! If there are any other issues, feel free to report them here!
