### ISSUE TITLE
Nut leaf blocks not having item form causing issues

### ISSUE THREAD

**Issue by Robosium** [DakotaPride/create-garnished#19]
Issue is especially apparent when using Immersive Weathering, game crashes when it attempts to show the nut leaf variant of the leaf pile item.

Besides it'd be cool to be able to place down the nut leaves where ever you want.

**Comment by DakotaPride** [comment]
This is coming in the next update, thank you for your feedback!

**Comment by DakotaPride** [comment]
Should be fixed now!
