### ISSUE TITLE
Compatibility issue due to wrong item tag?

### ISSUE THREAD

**Issue by Zartrix** [DakotaPride/create-garnished#21]
(All mods running on latest 1.20.1 version, Forge 47.2.0)
When using [Every Compat](https://modrinth.com/mod/every-compat), Create, Garnished and [MrCrayfish Furniture](https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod), the game crashes upon clicking/rendering hedges for all the nuts. This is easily avoidable though through Every Compats config where they can just be disabled.

The main issue I'm having is that the Sepia Stem and the Stripped Sepia Stem (Hyphae probably has the same issue?) not being registered correctly by the game, resulting in a lot of the furniture missing or using oak as fallback texture. Is it because their item tag is "#garnished:sepia_logs" instead of "#garnished:sepia_stems"?

Also, when throwing in [Supplementaries](https://modrinth.com/mod/supplementaries) into the mix of mods, the log even spits out a warning:

`[Render thread/WARN] [Supplementaries/]: Failed to generate hanging sign extension texture for garnished:sepia. Could be that the target mod isnt registering their wood type properly
java.lang.NullPointerException: Cannot invoke "net.minecraft.client.resources.model.Material.m_119203_()" because the return value of "net.minecraft.client.renderer.Sheets.m_246984_(net.minecraft.world.level.block.state.properties.WoodType)" is null`

I hope this helps in someway or another to hopefully fix this. If logs or anything else is needed, I'll provide it!

**Comment by DakotaPride** [comment]
This should be plenty of information, for the time being at least. The issue with the hedges might be caused because an item doesn't exist for them in the most recently released version of Garnished. This is being changed in the next update, however, so hopefully the issue will be fixed alongside it.
As for the sepia stems, I'm not entirely sure as to why it would be causing an issue, but I will try your suggestion of changing the tag name.
And then is the game crashing or doing anything else weird when it comes to loading it with Supplementaries and Garnished installed? A hanging sign for the Sepia wood type is not currently implemented (will most likely also be added in the next update), which is probably the reason why you're receiving that error to begin with.

For the time being, I'd suggest continuing to do what you've done to solve these errors (disabling it in the Every Compat config for example). Let me know if you have any other questions or concerns, I'll be sure to let you know when these issues are resolved!

**Comment by DakotaPride** [comment]
Apologies, but which mod adds the hedges that you are referring to? It doesn't seem like those are automatically generated with the mods listed.

**Comment by Zartrix** [comment]
No, Supplementaries and Garnished do nothing unusual on their own. The crash only occurs with the non-existent hedges when they are loaded. Altough the item Shelf and Sign Post from Supplementaries generate Sepia Variants normally unlike Every Compat and MrCrayfish Furniture, interestingly enough.

**Comment by DakotaPride** [comment]
It is certainly weird. I'm currently talking with the dev to try and figure it out so that built-in support can hopefully be implemented. Thank you for your patience and understanding regarding this!

**Comment by Zartrix** [comment]
No problem! I'm happy to somewhat help. Appreciate your work and looking forward to updates!

**Comment by DakotaPride** [comment]
Let me know if it's still broken even after updating!

**Comment by Zartrix** [comment]
I tried the same setup as originally, just with downgrading Create to .d. Hedges now "[work](https://i.imgur.com/xRFnLOr.png)" without disabling them and them crashing the game. Stripped Sepia is still [not being recognized,](https://i.imgur.com/s07XF41.png) sadly. Uses Stripped Oak as fallback. All Stripped variants for Furniture are still missing.

Supplementaries is also still looking for it, like in the original report.
> `[Render thread/WARN] [Supplementaries/]: Failed to generate hanging sign extension texture for garnished:sepia. Could be that the target mod isnt registering their wood type properly java.lang.NullPointerException: Cannot invoke "net.minecraft.client.resources.model.Material.m_119203_()" because the return value of "net.minecraft.client.renderer.Sheets.m_246984_(net.minecraft.world.level.block.state.properties.WoodType)" is null`

It would've used stripped Sepia to make hanging signs automatically if a mods wood set does not have it. Just how with Every Compat the other Furniture sets would "generate" if you can call it that.

**Comment by DakotaPride** [comment]
Not sure why, a fix was pushed to Moonlight Lib. Have you updated that?

**Comment by Zartrix** [comment]
Yes, I try to keep everything on the latest version. Exception being Create for now, obviously. Using Moonlight Lib 2.8.49. Even tried with a fresh instance for Forge. Don't know if there is something I can do or have to do on my end?

**Comment by DakotaPride** [comment]
There's not really much else I can do without having to refactor the entire wood set, which would delete any pre-existing instance of the Sepia stems/hyphae in anyone's world. I think you may have to, unfortunately, just disable sepia inside of the config. As for the leaves, the same goes for that as well, unfortunately.

**Comment by Zartrix** [comment]
I know this is closed, but I just wanted to add, that there seems to be an issue with some mods that add some sort of stem, be it from the nether or not. So this issue might not be entirely on your side!

**Comment by DakotaPride** [comment]
I remember talking with the developer, and they said that they had added "stem" and "hyphae" to the word detection list. If it is truly an issue non-exclusive to Garnished, then it is out of my control. Apologies for this, but I would recommend creating a report with the "Every Compat" developer/GitHub page.

**Comment by Zartrix** [comment]
Oh yeah, no worries, just wanted to let you know! I want to dig a bit more into this before creating the report to have it as much information as possible. Thank you for looking into it as much as you, were able to!
