### ISSUE TITLE
Crash on startup - Garnished 1.0

### ISSUE THREAD

**Issue by Zartrix** [DakotaPride/create-garnished#22]
Minecraft just crashes instantly. Using latest Create, Garnished and Forge 47.2.0

I don't know if this may be the main culprit, but it does not look right (Got this error by accidentally only launching Garnished)

`[main/ERROR] [ne.mi.fm.lo.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'create', Requested by: 'garnished', Expected range: '[0.5.0.i,)', Actual version: '[MISSING]'`

https://mclo.gs/iaQM7lH

**Comment by DakotaPride** [comment]
Try downgrading to anything below Create 0.5.1e, as there is a known incompatibility between Garnished and this version of Create. It will be fixed once the Fabric version of Create updates to 0.5.1e.
