### ISSUE TITLE
Bugged Sepia Door Texture (1.18.2)

### ISSUE THREAD

**Issue by Hukumaka** [DakotaPride/create-garnished#25]
Garnished: 1.1+1.18.2
Forge: 40.2.9
There is no texture when Sepia Door is placed

![2023-10-20_17 00 11](https://github.com/DakotaPride/create-garnished/assets/148560899/dabb99cc-60a6-4f72-a60c-391d7013ff29)

**Comment by DakotaPride** [comment]
Thank you for reporting this issue, a fix should become available soon!

**Comment by DakotaPride** [comment]
Currently, v1.1-hotfix is awaiting approval on Curseforge, but is available on [Modrinth (Both forge & fabric/quilt)](https://modrinth.com/mod/create-garnished/version/SFHzZoZA)!
