### ISSUE TITLE
Nut Leaves texture is bugged with Low quality leaves settings (1.18.2)

### ISSUE THREAD

**Issue by Hukumaka** [DakotaPride/create-garnished#26]
Garnished: 1.1+1.18.2
Forge: 40.2.9
Nut Leaves texture is bugged with Low quality leaves settings
![2023-10-20_17 00 51](https://github.com/DakotaPride/create-garnished/assets/148560899/5a453a66-2d20-48e3-a26d-aace5255a83a)

**Comment by DakotaPride** [comment]
This is something that, unfortunately, cannot be fixed and is not exclusive to 1.18.2. Apologies for the inconvenience, but you will have to play with Fancy graphics
