### ISSUE TITLE
Empty tag for some Farmers Delight recipes (1.18.2)

### ISSUE THREAD

**Issue by Hukumaka** [DakotaPride/create-garnished#27]
Garnished: 1.1+1.18.2
Forge: 40.2.9
Farmer's Delight: 1.2.3
Empty tag for some Farmer's Delight recipes
![2023-10-20_17 38 00](https://github.com/DakotaPride/create-garnished/assets/148560899/432431da-2bf6-4713-9388-0b3f6eaaf91f)

**Comment by DakotaPride** [comment]
Thank you for reporting this issue! This should be fixed in the next update!

**Comment by DakotaPride** [comment]
Currently, v1.1-hotfix is awaiting approval on Curseforge, but is available on [Modrinth (Both forge & fabric/quilt)](https://modrinth.com/mod/create-garnished/version/SFHzZoZA)!
