### ISSUE TITLE
Nut trees seems to not generate naturally (1.18.2)

### ISSUE THREAD

**Issue by Hukumaka** [DakotaPride/create-garnished#28]
Garnished: 1.1+1.18.2
Forge: 40.2.9
Nut trees seems to not generate naturally
Can't find any in new generated worlds

**Comment by DakotaPride** [comment]
This may take some time to fix, as 1.18.2's worldgen is very wonky (in general). So apologies for the inconvenience, and thank you for you patience and understanding!

**Comment by DakotaPride** [comment]
After many hours of debugging and porting the ResourceKey system back to RegistryObject, this issue should be fixed in the next update!

**Comment by DakotaPride** [comment]
Currently, v1.1-hotfix is awaiting approval on Curseforge, but is available on [Modrinth (Both forge & fabric/quilt)](https://modrinth.com/mod/create-garnished/version/SFHzZoZA)!
