### ISSUE TITLE
Crashing on Startup

### ISSUE THREAD

**Issue by YukiRainee** [DakotaPride/create-garnished#29]
Seems like I'm crashing on startup 
https://mclo.gs/RLntCrP
Decided to post just in case it might be unknown but looking at the current issues here it seems like it is similar to #17 if so why not just update it seems like fabric version won't be updated for a while

**Comment by DakotaPride** [comment]
I would like to keep both the Forge & Fabric versions up to date with each other. I understand that this may be frustrating, but I can assure you that a fix will be released once the Fabric version is updated. Any updates regarding the issue will most likely be posted in #17

**Comment by DakotaPride** [comment]
Should be fixed now, let me know if you still experience issues!
