### ISSUE TITLE
Compatibility with expanded delights?

### ISSUE THREAD

**Issue by NolanHewitt** [DakotaPride/create-garnished#30]
Not sure if this is possible or if this is too big of a request, but the expanded delight fabric mod (https://www.curseforge.com/minecraft/mc-mods/expanded-delight) adds a couple of items that are already in this mod, namely salt and peanuts. Is there any chance you could add some kind of recipe compatibility so that the items from both mods could be used interchangeably?

**Comment by DakotaPride** [comment]
I'm able to add Expanded Delight's items to my recipes, but using items introduced in Garnished with Expanded Delight is something that the Expanded Delight developer will have to do. I can try to make a pull request over there to see what I can do, but I can't guarantee that it'll be merged.

Some of the items that aren't used have to do with tagging, so it's an easy fix for the most part.

edit: update to when these changes will be released, a hotfix will be released later on when the pull request on the Expanded Delight GitHub page has been reviewed and potentially merged.

**Comment by DakotaPride** [comment]
Here is a current list of items that can be used for compatibility, let me know if there are any missing! (compatibility will most likely be released later on once Create Fabric updates to 0.5.1e)

- [Garnished] "garnished:crushable/peanut" tag added to c:crops/peanuts tag
- [Garnished] Almond cheese added to c:cheese tag
- [Garnished] Adjust recipes that utilize "garnished:almond_cheese" to instead use "c:cheese"
- [Garnished] Adjust recipes that utilize "garnished:crushable/peanut" to instead use "c:crops/peanuts"
- [Garnished] The above examples exclude some other recipes/recipe types (such as "filling" or "application" recipes involving peanuts)
- [Expanded Delight] Cheese Slice added to c:cheese tag
- [Expanded Delight] Adjust recipes that utilize "expandeddelight:cheese_slice" to instead use "c:cheese"

**Comment by NolanHewitt** [comment]
Oh wow, that was fast! That list looks perfect! Thank you for going above and beyond and also submitting a pull request to expanded delights too!

**Comment by DakotaPride** [comment]
While the pull request hasn't yet been merged, I've updated Create: Garnished to include the changes. You will still have to wait for Expanded Delight to update, however.
