### ISSUE TITLE
Apple Cider + Lava = Cobblestone?

### ISSUE THREAD

**Issue by annaleighsmith** [DakotaPride/create-garnished#31]
Hello I am playing with Fabric 0.14.22, Minecraft 1.19.2 with Create Garnished 1.2-hotfix-2+1.19.2 and Create 0.5.1C and when I use apple cider and lava I am getting cobblestone, The other combinations for calcite and dripstone (garnish and peanut oil) are working though. I was following a video, is this a bug?

**Comment by DakotaPride** [comment]
Could you provide the video that you were following? Testing this (on my end) seems to produce the below results.

Both taking an input from the side and top produce Ochrum in the image below.
![2023-11-07_07 02 15](https://github.com/DakotaPride/create-garnished/assets/82760983/7023a2e6-a077-4de0-b8de-ba82dcb66c9f)

**Comment by annaleighsmith** [comment]
https://www.youtube.com/watch?v=ixdMESO_tjs This video around 10 minutes in, I can send you a screenshot of me trying and a modpack, my server has a significant amount of mods so maybe there's a incompatibility issue there.

**Comment by annaleighsmith** [comment]
I see we have delightful creators mod, it thinks Apple Cider bucket is from that mod.

**Comment by DakotaPride** [comment]
I'll have to look further into it, but it is possible. I'll make sure to let you know as soon as I can test it!  (currently away from my computer)

**Comment by annaleighsmith** [comment]
![2023-11-08_22 11 37](https://github.com/DakotaPride/create-garnished/assets/87508728/9777e075-cadf-4f6e-b267-62f5a1bae7fc)
![2023-11-08_22 10 32_2](https://github.com/DakotaPride/create-garnished/assets/87508728/90d37a3f-d07e-4216-8ebc-d3f548ed52cb)
There is my machine with peanut oil working normally and apple cider - cobble

**Comment by annaleighsmith** [comment]
Cool! Love your mod, just let me know if you need any more information :)

**Comment by DakotaPride** [comment]
Could you show the recipe that you're using to make the apple cider? Preferably in JEI or other recipe viewer for ease of access.

**Comment by annaleighsmith** [comment]
Ah I'm realizing what it is. I feel silly sorry, delightful creators has a separate different recipe for apple cider, its working
