### ISSUE TITLE
Conflict Between AE2 Ender Dust and Garnished Ender Dust

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [DakotaPride/create-garnished#33]
Minecraft: 1.20.1
Forge: 47.2.0
Mod Version: 1.2-hotfix-2+1.20.1

I was playing modpack that has AE2 Installed, but there are 2 Ender Dust Types, Which aren't compatible with each other. 
This results in AE2 being prioritized, making Garnished Ender Dust Impossible to Craft.
![image](https://github.com/DakotaPride/create-garnished/assets/40109698/52fa3116-7193-4d67-98c7-61d82d0351e3)
![image](https://github.com/DakotaPride/create-garnished/assets/40109698/6231eb7d-dc57-4b36-a4c0-57ef8762616f)

**Comment by DakotaPride** [comment]
Thank you for bringing this to my attention! Luckily, this can be "fixed" on my end pretty easily by simply adding a common/forge tag for ender_dusts and then changing any related recipes. In terms of AE recipes, however, that would have to be something to take to the AE devs/GitHub issues page. With that being said, I'll let you know when the next version becomes available.

It's worth noting that the recipe will still function the same (so the conflict still exists, unfortunately), you will just be able to use mostly any ender dust for related recipes that require ender dust.

**Comment by DakotaPride** [comment]
Apologies for the late response, but v1.3 is released!
