### ISSUE TITLE
Mud Pie Crash

### ISSUE THREAD

**Issue by Waffz** [DakotaPride/create-garnished#36]
Mud Pie/Mulch Crash when eating using a small/simple create mod pack (Quilt/Fabric 1.20.1)

[crash-2023-12-16_00.05.41-server.txt](https://github.com/DakotaPride/create-garnished/files/13691673/crash-2023-12-16_00.05.41-server.txt)

**Comment by DakotaPride** [comment]
Should be fixed in the next update, will let you know when it's released!

**Comment by DakotaPride** [comment]
Should be fixed now, please let me know if there are any other issues or if this one persists!
