### ISSUE TITLE
Some items/advancements/ponders are missing proper text or names

### ISSUE THREAD

**Issue by Hukumaka** [DakotaPride/create-garnished#38]
Forge 1.20.1
Garnished 1.5+1.20.1-beta

Some items/advancements/ponders are missing proper text or names

![2024-01-05_17 34 22](https://github.com/DakotaPride/create-garnished/assets/148560899/050d1cbb-fc24-4fd7-a5c4-7e371b3b3e06)
![2024-01-05_17 34 48](https://github.com/DakotaPride/create-garnished/assets/148560899/ac41b00a-8782-45e1-b067-a3adb2be1ae3)

**Comment by DakotaPride** [comment]
Thank you for letting me know, but this issue is currently already being looked at. It should be fixed in the next update, of which I'll try to let you know when it releases!

**Comment by DakotaPride** [comment]
Both issues (this one and #39) should be fixed now!
