### ISSUE TITLE
Voltaic Sea Grass is missing it's texture

### ISSUE THREAD

**Issue by Hukumaka** [DakotaPride/create-garnished#39]
Forge 1.20.1
Garnished 1.5+1.20.1-beta

Voltaic Sea Grass is missing it's texture

![2024-01-05_17 33 47](https://github.com/DakotaPride/create-garnished/assets/148560899/5f331218-8dc0-472e-9eac-98ee4e111c6c)

**Comment by DakotaPride** [comment]
This issue should be fixed in the next update! Thank you for letting me know!
