### ISSUE TITLE
Cashew and Chestnut trees and leaves doesn't drop their respective nuts in 1.19.2

### ISSUE THREAD

**Issue by TimBranger27** [DakotaPride/create-garnished#40]
As I wrote, cashew and chestnut trees and leaves doesn't drop their nuts. All other nut leaves do, but these two do not. 
Im on fabric loader version 15.3 in minecraft version 1.19.2. 

Please help, thanks.

The mods i use are:

  [✔] Adorn-3.9.1+1.19.2-fabric
  [✔] appleskin-fabric-mc1.19.2-2.5.1
  [✔] Applied-Botanics-fabric-1.4.6
  [✔] appliedenergistics2-fabric-12.9.8
  [✔] architects-palette-fabric-3.0.0
  [✔] architectury-6.5.85-fabric
  [✔] balm-fabric-1.19.2-4.6.0
  [✔] banner-flags-1.4
  [✔] bellsandwhistles-0.4.4+1.19.2-12
  [✔] Bookshelf-Fabric-1.19.2-16.3.20
  [✔] Botania-1.19.2-440-FABRIC
  [✔] builderwands-1.0.0
  [✔] bundle_jumble-1.0.0-mc1.19
  [✔] bushierflowers-0.0.1-1.19.2
  [✔] camerautils-fabric-1.19.2-1.0.8
  [✔] cardinal-components-api-5.0.2
  [✔] carpet-extra-1.19.2-1.4.84
  [✔] chipped-fabric-1.19.2-2.1.5
  [✔] cloth-config-8.3.115-fabric
  [✔] Clumps-fabric-1.19.2-9.0.0+14
  [✔] compressed-2.0.0
  [✔] configured-fabric-2.0.0-1.19.2
  [✔] connectiblechains-2.1.4+1.19.2
  [✔] continuity-2.0.2+1.19
  [✔] Controlling-fabric-1.19.2-10.0+7
  [✔] create_enchantment_industry-1.0.1.b
  [✔] create-fabric-0.5.1-c-build.1160+mc1.19.2
  [✔] create-renewable-ores-1
  [✔] createaddition-fabric+1.19.2-20230723a
  [✔] createutilities-0.1.3+1.19.2
  [✔] ctm-refabricated-1.0.1+1.19
  [✔] dashloader-4.1.3+1.19
  [✔] Decorative+Blocks-fabric-1.19.2-3.1.1
  [✔] DeepslateInstamine_mc1.19.2-2.5_release-fabric
  [✔] DisableCustomWorldsAdvice-3.0
  [✔] do-a-barrel-roll-2.6.2+1.19.2-fabric
  [✔] dynamic-fps-3.3.2+minecraft-1.19.0
  [✔] EasyAnvils-v4.0.11-1.19.2-Fabric
  [✔] elytraslot-fabric-6.1.1+1.19.2
  [✔] EnchantmentDescriptions-Fabric-1.19.2-13.0.14
  [✔] enderchests-fabric-1.19.2-1.1.7
  [✔] entityculling-fabric-1.6.1-mc1.19.2
  [✔] expanded-trident-enchanting-1.0.4
  [✔] ExplorersCompass-1.19.2-2.2.0-fabric
  [✔] ExtendedDrawers-1.4.5+mc.1.19.2
  [✔] extendedgears-2.1.0-1.19.2-0.5.1.c-fabric
  [✔] extremesoundmuffler-3.39-fabric-1.19.2
  [✔] fabric-api-0.76.1+1.19.2
  [✔] fabric-carpet-1.19.2-1.4.84+v221018
  [✔] fabric-language-kotlin-1.10.17+kotlin.1.9.22
  [✔] fabric-language-kotlin-1.10.8+kotlin.1.9.0
  [✔] fabrication-3.4.0+1.19
  [✔] farmers-delight-fabric-1.3.10.2
  [✔] ForgeConfigAPIPort-v4.2.11-1.19.2-Fabric
  [✔] ftb-chunks-fabric-1902.4.4-build.326
  [✔] ftb-library-fabric-1902.4.1-build.236
  [✔] ftb-teams-fabric-1902.2.14-build.123
  [✔] garnished-1.5.1-hotfix-1+1.19.2
  [✔] ImmediatelyFast-Fabric-1.2.8+1.19.2
  [✔] immersive_paintings-0.6.7+1.19.2-fabric
  [✔] indium-1.0.9+mc1.19.2
  [✔] Infinity-Water-Bucket-Fabric-1.19-2.0.0
  [✔] infinityfix-1.0.1
  [✔] infinitymendingbow-1.0
  [✔] inventorio-1.19-fabric-1.9.1
  [✔] iris-mc1.19.2-1.6.11
  [✔] itemscroller-fabric-1.19.2-0.17.1
  [✔] itemswapper-fabric-0.4.0-mc1.19.2
  [✔] Jade-1.19.1-fabric-8.7.3
  [✔] JadeAddons-1.19.2-fabric-3.2.0
  [✔] Kiwi-1.19.1-fabric-8.3.4
  [✔] lambdynamiclights-2.2.0+1.19.2
  [✔] litematica-fabric-1.19.2-0.12.7
  [✔] lithium-fabric-mc1.19.2-0.11.1
  [✔] malilib-fabric-1.19.2-0.13.0
  [✔] ManaVisualizer-1.1+1.19.2
  [✔] mcpitanlibarch-1.8.4-1.19.2-fabric
  [✔] megacells-fabric-2.0.4-1.19.2
  [✔] minihud-fabric-1.19.2-0.23.3
  [✔] modmenu-4.2.0-beta.2
  [✔] moonlight-1.19.2-2.3.5-fabric
  [✔] MoreGems-Fabric-1.19.2-1.4.53
  [✔] MouseTweaks-fabric-mc1.19-2.22
  [✔] mousewheelie-1.13.0+mc1.19.2
  [✔] NaturesCompass-1.19.2-2.1.0-fabric
  [✔] Nullscape_1.19.3_v1.2.2
  [✔] owo-lib-0.9.3+1.19
  [✔] Patchouli-1.19.2-77-FABRIC
  [✔] piglessportals-1.1.1
  [✔] polymorph-fabric-0.46.5+1.19.2
  [✔] Powah-4.0.11
  [✔] PuzzlesLib-v4.4.3-1.19.2-Fabric
  [✔] RebornCore-5.4.0
  [✔] reeses_sodium_options-1.6.4+mc1.19.2-build.93
  [✔] reinforced-barrels-2.3.0+1.19
  [✔] reinforced-chests-2.2.0+1.19
  [✔] reinforced-shulker-boxes-2.2.0+1.19
  [✔] replaymod-1.19.2-2.6.14
  [✔] resourcefullib-fabric-1.19.2-1.1.24
  [✔] RoughlyEnoughItems-9.1.682-fabric
  [✔] RoughlyEnoughLootTables-1.19-1.0
  [✔] RoughlyEnoughProfessions-fabric-1.19.2-1.1.4
  [✔] RoughlyEnoughTrades-1.19-1.0
  [✔] shetiphiancore-fabric-1.19.2-1.3.12
  [✔] simplemagnets-1.1.10-fabric-mc1.19.2
  [✔] simplevillagers-1.4.1
  [✔] sliceanddice-fabric-2.3.2
  [✔] smoothboot-fabric-1.19-1.7.1
  [✔] SnowRealMagic-1.19.2-fabric-5.1.2
  [✔] sodium-extra-0.4.16+mc1.19.2-build.90
  [✔] sodium-fabric-mc1.19.2-0.4.4+build.18
  [✔] spiceoffabric-1.6.2+mc1.19.2
  [✔] Steam_Rails-1.5.1+fabric-mc1.19.2
  [✔] supermartijn642configlib-1.1.8a-fabric-mc1.19
  [✔] supermartijn642corelib-1.1.16-fabric-mc1.19.2
  [✔] supplementaries-1.19.2-2.4.15-fabric
  [✔] TechReborn-5.4.0
  [✔] tooltipfix-1.1.1-1.19
  [✔] trashcans-1.0.18-fabric-mc1.19.2
  [✔] travelers-backpack-1.19.2-8.2.33
  [✔] trinkets-3.4.2
  [✔] tweakeroo-fabric-1.19.2-0.14.3
  [✔] way_much_faster_oxidize-1.19.2-1.1.1
  [✔] waystones-fabric-1.19.2-11.4.2
  [✔] worldedit-mod-7.2.12
  [✔] Xaeros_Minimap_23.9.3_Fabric_1.19.1
  [✔] XaerosWorldMap_1.37.2_Fabric_1.19.1

(btw love this mod)

**Comment by DakotaPride** [comment]
A bugfix is available on Modrinth, curseforge release is currently waiting for approval!

edit: Curseforge has been approved!

**Comment by TimBranger27** [comment]
Thanks a lot man
