### ISSUE TITLE
Conflict with SeparatedLeaves causes most nut tree leaves immediately decay (1.20.1)

### ISSUE THREAD

**Issue by RowanSkie** [DakotaPride/create-garnished#41]
(Necessary logs just in case: https://mclo.gs/2WxVlKa)

I've noticed in my playthrough that most of the nut trees immediately have their leaves start despawning save for a few leaves connected directly to the wood itself. It also happens on trees when planted with specific nuts.

Found the conflict! It's https://github.com/TeamDiopside/SeparatedLeaves.

**Comment by DakotaPride** [comment]
Pull request made: https://github.com/TeamDiopside/SeparatedLeaves/pull/7
