### ISSUE TITLE
Latest Release Broke Pickaxes

### ISSUE THREAD

**Issue by GamingEinstein** [DakotaPride/create-garnished#42]
On the latest release of the mod (1.5.2+1.20.1), there seems to be a bug that prevents Pickaxes from being able to mine anything at the speed or drop the items they're supposed to. Shovels and Axes seem to be fine, but mods that add items that act like pickaxes (like Paxels or Create: Stuff and Additions Portable Drill) are also affected. It seems something is preventing these items from registering as Pickaxes as evident when using Jade. This bug is not present on 1.5.1-hotfix-1+1.20.1

![2024-01-19_16 11 35](https://github.com/DakotaPride/create-garnished/assets/78991053/cc47167a-e32a-480a-8cd3-52712c0183d0)
![2024-01-19_16 11 47](https://github.com/DakotaPride/create-garnished/assets/78991053/fecdb92f-9c44-4a8a-aa60-f89d6bfc0ad7)
![2024-01-19_16 11 50](https://github.com/DakotaPride/create-garnished/assets/78991053/865a7fec-d9af-43b3-ab24-ef6f4551b564)

Mods used (this was tested with just Create and Garnished with the same results):
- Create
- Create Garnished
- Create Stuff and Additions
- Jade
- Easy Paxels Lite

**Comment by LeyKlussyn** [comment]
Having the same issue: Pickaxes stopped working after doing the 1.5.2 update (1.20.1), main mods only Create and Garnished. (I don't have Stuff and Additions, Jade or Easy Paxels Lite)

**Comment by DakotaPride** [comment]
Could you show your latest.log file? I'm pretty confident that I know what the error is, but just want confirmation first.

**Comment by LeyKlussyn** [comment]
@DakotaPride Here you go
[latest.log](https://github.com/DakotaPride/create-garnished/files/13995923/latest.log)

**Comment by DakotaPride** [comment]
Thank you! A fix should be out in a little bit! (may take some time to make it onto Curseforge, however)

**Comment by Nycto97** [comment]
> Thank you! A fix should be out in a little bit! (may take some time to make it onto Curseforge, however)

Thanks! Was searching this issue as well. Glad I found it :)

Edit: I'm on 1.19.2 where the issue also occurs

**Comment by DakotaPride** [comment]
> > Thank you! A fix should be out in a little bit! (may take some time to make it onto Curseforge, however)
> 
> Thanks! Was searching this issue as well. Glad I found it :)
> 
> Edit: I'm on 1.19.2 where the issue also occurs

The issue seems to occur when any version aside from Fabric 1.20.1, since there was a typo in one of the tags (which translated to most of the other versions)

**Comment by DakotaPride** [comment]
Should now be available on Modrinth and Curseforge
