### ISSUE TITLE
Latest Version of garnished Stone Breaking problem

### ISSUE THREAD

**Issue by f0kx** [DakotaPride/create-garnished#45]
After updating to the latest Version of garnished i cant break any stones any more
1.5.2 broke all stone gatering
1.4 is working

**Comment by f0kx** [comment]
iam on version 1.19.2 with Forge 43.3.5

**Comment by DakotaPride** [comment]
The latest version is v1.5.2-hotfix-1, let me know if the issue persists after updating

**Comment by f0kx** [comment]
![image](https://github.com/DakotaPride/create-garnished/assets/14795020/172782b9-988d-4646-943b-111328f62775)
the latest is labeled fabric but i have forge

**Comment by DakotaPride** [comment]
There is a forge version listed as well [here](https://www.curseforge.com/minecraft/mc-mods/garnished/files/5046441)

**Comment by f0kx** [comment]
it wasnt there a swear 
![image](https://github.com/DakotaPride/create-garnished/assets/14795020/13e70bd9-2948-4243-b7c9-022c5970c13b)
only 4 downloads do you upload it recently?

**Comment by DakotaPride** [comment]
"Jan 20, 2024" (so yesterday) might not be very popular on Curseforge for some reason

**Comment by f0kx** [comment]
![image](https://github.com/DakotaPride/create-garnished/assets/14795020/90433aa9-fa41-4d17-9573-a43a52b99723)
this is what i see in curse launcher app there is no fixed version

**Comment by f0kx** [comment]
ahh you labeled it 1.20 so thats the reason
![image](https://github.com/DakotaPride/create-garnished/assets/14795020/06903ed8-b5f8-4d84-aa46-e8c7e814dadf)

supported version 1.20. & 1.20.1

**Comment by DakotaPride** [comment]
Ah, apologies. Should be fixed soon!

**Comment by DakotaPride** [comment]
Should work now, let me know if the issue still occurs!

**Comment by f0kx** [comment]
yeah its working now thank you <3
