### ISSUE TITLE
Crash with Create Patch F 1.20.1

### ISSUE THREAD

**Issue by NolanHewitt** [DakotaPride/create-garnished#48]
Crashes on startup

**Comment by DakotaPride** [comment]
Please provide the crash report, otherwise I cannot help you. If this information is not provided within a reasonable timeframe (1 week), this issue will be closed due to lack of information.

**Comment by NolanHewitt** [comment]
[latest.log](https://github.com/DakotaPride/create-garnished/files/14549053/latest.log)
[crash-2024-03-09_23.50.04.0514-quilt_loader.txt](https://github.com/DakotaPride/create-garnished/files/14549054/crash-2024-03-09_23.50.04.0514-quilt_loader.txt)
Here are the latest.log and crash log

**Comment by DakotaPride** [comment]
For the time being, you will have to be on the previous version of Create Fabric until I can update the methods used within Create: Garnished. Apologies for the inconvenience, but the next update should be released within the next month if all things go well with development!

**Comment by NolanHewitt** [comment]
No worries, thanks for the update on what's happening

**Comment by DakotaPride** [comment]
If you'd like, I occasionally post test builds on the Create: Garnished discord server, of which I posted v1.7 builds last night that should work with the latest Create Fabric version.

**Comment by NolanHewitt** [comment]
Hey thanks, I'll check that out!

**Comment by DakotaPride** [comment]
Should be fixed now! Let me know if it still happens or if any other issues arise!

**Comment by NolanHewitt** [comment]
> Should be fixed now! Let me know if it still happens or if any other issues arise!

The new version does look like it works with the new create version! Though it seems the new items have missing icons and models? 
![huge_2024-03-14_01 23 32](https://github.com/DakotaPride/create-garnished/assets/52480898/dc0f960d-2890-4247-b975-5d2333c77cdb)
