### ISSUE TITLE
Use loot tables for scavenging/ravaging drops

### ISSUE THREAD

**Issue by medsal15** [DakotaPride/create-garnished#49]

**Comment by DakotaPride** [comment]
Is there any reason in particular why you thunk that I should migrate my current code over to being loot tables?

**Comment by medsal15** [comment]
It would be more explicit for datapack making, as searching for where some items are from is hard without any indication.

It would also allow adding more entities for specific drops.

**Comment by DakotaPride** [comment]
Even though this doesn't change much about gameplay, I thought that I'd let you know that the Modrinth files are available and that the Curseforge files are currently waiting to be approved, in case you want to do anything, in particular, utilizing these changes.
