### ISSUE TITLE
Nut trees grow in strange places.

### ISSUE THREAD

**Issue by seaseii** [DakotaPride/create-garnished#5]
![1](https://github.com/DakotaPride/create-garnished/assets/114800774/10bbe950-255e-4bb4-8517-42cf7fc3c403)
It's cool.
And the leaves with nuts seem unnamed,
![2](https://github.com/DakotaPride/create-garnished/assets/114800774/16138bf2-a073-4b71-90ab-3e88321248ff)

**Comment by seaseii** [comment]
These trees grow disorderly in the water, and the number they produce is really large.

**Comment by seaseii** [comment]
Even growing on another tree
![3](https://github.com/DakotaPride/create-garnished/assets/114800774/c1a10806-4a0a-4444-84f7-f581a12c0078)

**Comment by DakotaPride** [comment]
Some other issues are currently being resolved regarding both the Fabric and Forge versions, so it may be a while until v0.6.1 is released (apologies for that). But, when it does release, this should be fixed. I can't currently give a specific time/date for this, however, but expect it in the next coming days. Thank you for your patience, and again, apologies for the inconvenience! I'll make sure to let you know when a bug fix is publicly available!

**Comment by seaseii** [comment]
> Some other issues are currently being resolved regarding both the Fabric and Forge versions, so it may be a while until v0.6.1 is released (apologies for that). But, when it does release, this should be fixed. I can't currently give a specific time/date for this, however, but expect it in the next coming days. Thank you for your patience, and again, apologies for the inconvenience! I'll make sure to let you know when a bug fix is publicly available!

Thx : )

**Comment by DakotaPride** [comment]
Apologies for the wait, but a bugfix is available on modrinth. Thank you for your patience and understanding!

**Comment by seaseii** [comment]
> Apologies for the wait, but a bugfix is available on modrinth. Thank you for your patience and understanding!很抱歉等待，但 modrinth 上有一个错误修复。感谢您的耐心和理解！

I've already seen it,very thanks!
