### ISSUE TITLE
Bulk freezing comptability with Create Dreams & Desires

### ISSUE THREAD

**Issue by medsal15** [DakotaPride/create-garnished#50]
[Create: Dreams & Desires](https://modrinth.com/mod/create-dreams-and-desires) also adds its own bulk freezing method, and a custom fan for processing.

**Comment by DakotaPride** [comment]
I have gotten this request a decent bit. Could you elaborate further on what exactly you're wanting/you mean by this?

**Comment by medsal15** [comment]
Both use a different recipe type for what is effectively the same processing, powdered snow in front of a fan. I would like to have an option to hide one's tab in JEI and have its fan in the other's list.

**Comment by DakotaPride** [comment]
The issue with that is that D&D utilizes a different fan for it's freezing, and has different recipes for that specific recipe type. So hiding one tab would mean that certain recipes are never interacted with.
