### ISSUE TITLE
Texture of 1.7+1.20.1 (Fabric) are missing

### ISSUE THREAD

**Issue by MrRedstoneToGo** [DakotaPride/create-garnished#51]
Look at this:
![2024-03-14_20 37 32](https://github.com/DakotaPride/create-garnished/assets/163460667/2931f0db-40f9-4697-b9b0-bbbd0c139d2e)
It's the Frosted Apple Recipe. Why is it an Manual item application if you cannot place apples?! Change it to a deploying recipe!

Anyway, cool mod

**Comment by DakotaPride** [comment]
The texture issue is currently being looked into, and the item_application/deploying recipes should be fixed in the same hotfix release. Thank you!

**Comment by DakotaPride** [comment]
Modrinth files approved, though Curseforge has yet to be approved just yet!
