### ISSUE TITLE
[Additional Compat] EMI Support

### ISSUE THREAD

**Issue by MrRedstoneToGo** [DakotaPride/create-garnished#52]
Bulk dying (1.7+1.20.1; fabric) is very good way to recolor wool or glass but you have to install JEI alongside EMI o see them. Create Fabric has integration for EMI already. And if you're going to add new recipes with chance, EMI will factor them into the recipe tree instead of just ignoring them.

Thanks

**Comment by DakotaPride** [comment]
After a good bit and realizing that I was using the wrong Item Viewer class the entire time, I finally managed to get it working. Should be in the next hotfix, I'll make sure to let you know when it releases!
<img width="526" alt="image" src="https://github.com/DakotaPride/create-garnished/assets/82760983/0a064867-291c-4112-8163-263e4e699845">

**Comment by DakotaPride** [comment]
It should now be available on Modrinth, but Curseforge files are currently waiting for approval!

**Comment by MrRedstoneToGo** [comment]
I just noticed that you added the fluid combinations with lava. This was not expected but it's so useful. Thanks for this mod and these quick updates, how do you do that?

**Comment by DakotaPride** [comment]
No problem! I just really enjoy developing my projects, which can lead me to work all day on them and get maybe a little too much done

**Comment by MrRedstoneToGo** [comment]
Hello, there's a little bug left. If you go to the tuff world interaction recipe and click the recipe tree button on the right and want to produce 5 tuff, EMI will tell you that you need 5 liters of lava and and 5 liters of liquefied mastic resin. Please fix this. If you look at the cobble generator recipe on the same tab and hover over water or lava there's an arrow pointing to the right to the fluid. Add that and I am happy. (I'm already, but...)

**Comment by DakotaPride** [comment]
Could you provide screenshots of this issue? I checked myself and they seem normal.

<img width="345" alt="image" src="https://github.com/DakotaPride/create-garnished/assets/82760983/11f5096f-8e43-4ec2-99d2-4e69b1543693">
<img width="401" alt="image" src="https://github.com/DakotaPride/create-garnished/assets/82760983/916945d9-ce40-4eae-a39b-6731b50676b8">
<img width="350" alt="image" src="https://github.com/DakotaPride/create-garnished/assets/82760983/c850cadf-108a-417e-9209-9102bed17d5b">

**Comment by MrRedstoneToGo** [comment]
Adjust  the "x1" with the scroll wheel and you'll see...

**Comment by DakotaPride** [comment]
Logically speaking, it seems to work just fine. Though, I understand that this is something minor that could lead to confusion among players. I see that you've brought this to the attention of the Create devs as well, of which I'll probably wait for the issue to be fixed on their end since I used their classes for Create: Garnished EMI integration.
<img width="346" alt="image" src="https://github.com/DakotaPride/create-garnished/assets/82760983/3c32ed57-ff8b-45ea-b2ae-9a46d386658c">

**Comment by MrRedstoneToGo** [comment]
How many buckets of Lava or Mastic resin do you need for a Tuff generator? Two, not 10. Compare this to the cobblestone example. The thing with a cobble gen is that you have infinite cobblestone with just two fluid blocks. I mean: No matter how many blocks you need, there should always be 1000 L of liquid. You don't need to farm  a ton of slime balls for a ton of tuff, just 9 anyway. Someone could believe this recipe tree and farm a ton of slime balls and realize the work wasn't necessary.

**Comment by MrRedstoneToGo** [comment]
"Logically speaking, it seems to work just fine. Though, I understand that this is something minor that could lead to confusion among players. I see that you've brought this to the attention of the Create devs as well, of which I'll probably wait for the issue to be fixed on their end since I used their classes for Create: Garnished EMI integration."

And what if we do this otherwise? I know you are quicker. And when they copy your code they're quicker too. Don't take this personally.

**Comment by DakotaPride** [comment]
I can see what I can do, but if I end up not being able to fix it, I'll just wait.

**Comment by DakotaPride** [comment]
If I do find a fix, I'll make sure to make a pull request in the Create mod repository as well.

**Comment by MrRedstoneToGo** [comment]
Oh, look at EMI's code and search "cobblestone" . There's the way of the developer

**Comment by DakotaPride** [comment]
I think I found a way to fix it, I've made a pull request over on the Create Fabric repository. https://github.com/Fabricators-of-Create/Create/pull/1387

**Comment by DakotaPride** [comment]
[Create: Garnished] Files have been uploaded to Modrinth, Curseforge is waiting for approval!
