### ISSUE TITLE
Create: Garnished trees decay despite compatibility with Separated Leaves post-0.5.1f Fabric Update

### ISSUE THREAD

**Issue by RowanSkie** [DakotaPride/create-garnished#54]
After updating Create: Garnished and Create to 0.5.1f and the working respective version, compatibility with Separated Leaves broke. The previous compatibility issue is on #41.

**Comment by DakotaPride** [comment]
What version of Garnished are you on? It's always better to provide the exact version you're on as opposed to simply saying "the most recent," as sometimes you may still have the incorrect version. It's happened before, believe it or not.

 I'm not sure why it broke considering that nothing changed with the related tags or features in this update.

**Comment by RowanSkie** [comment]
I'm on Garnished 1.7.2.
![image](https://github.com/DakotaPride/create-garnished/assets/11764533/85935205-7ec1-4ba8-9671-14223c6b0735)

**Comment by DakotaPride** [comment]
Ah, after further examination of both the Garnished and Separated Leaves repositories, I think I missed an entry in the original pull request. I'll go ahead and submit that shortly and hopefully, they can merge soon after.

**Comment by DakotaPride** [comment]
Updated pull request made https://github.com/TeamDiopside/SeparatedLeaves/pull/12

**Comment by DakotaPride** [comment]
I'm gonna go ahead and close this issue, since there's not much else that I can do on my end, since the above pull request has not been merged yet. Let me know if you come across any other issues or if this one persists once/if Separated Leaves has updated

**Comment by DakotaPride** [comment]
Pull request seems to have been merged now. Once Separated Leaves officially releases an update, let me know if you still experience this issue!
