### ISSUE TITLE
Script (Wacatac.h!ml) virus

### ISSUE THREAD

**Issue by GORECKIPL** [DakotaPride/create-garnished#55]
![obraz](https://github.com/DakotaPride/create-garnished/assets/86680035/97fcba42-f61a-4b92-8a8f-26553ab61886)
 Mod have problem with Windows Defender.

**Comment by DakotaPride** [comment]
A similar issue came up by someone in the Discord, I can assure you that it is not a problem unique to Create: Garnished. As long as you downloaded from Curseforge, Modrinth, or Ko-fi, it should be safe. If you did not download from one of these three sources, please make sure to never download from prohibited websites or addresses, as I do not permit the usage of my work without my permission.
<img width="595" alt="image" src="https://github.com/DakotaPride/create-garnished/assets/82760983/76dfce4c-4eee-4544-ad8f-7a6579230c70">
