### ISSUE TITLE
Fish should gain immunity to Voltaic Sea Grass

### ISSUE THREAD

**Issue by NolanHewitt** [DakotaPride/create-garnished#56]
While funny, I often see mass hordes of fish dying in water because they don't know to avoid the sea grass. Perhaps fish could be given some kind of immunity to it to prevent the mass slaughter of fish in the future? Perhaps a tag could be used to decide if a fish mob is immune to it so support could also be easily added to fish from other mods as well.

**Comment by DakotaPride** [comment]
Should work now!
