### ISSUE TITLE
[Feature request] Add missing coloured Mastic Resin variants

### ISSUE THREAD

**Issue by MrRedstoneToGo** [DakotaPride/create-garnished#57]
As you may have noticed, you cannot bulk dye wool or glass pink but purple. This does not make sense! So I had the brainwave that you could mix colors by placing two or more coloured mastic resin blocks in the air flow of an encased fan. For pink dye, this means you place red and white resin and the particles turn pink after going through both liquids. This works with any dye you can craft with two or more dyes but only if there is a mastic resin variant. Cyan dye is blue dye and green dye mixed together, so you will need blue and green mastic resin.

The only problem is white, black and brown dye. They cannot be crafted with other dyes. White dye could be the new white chocolate, black dye could be dark chocolate and brown dye could be milk chocolate! This brings us back to the original title "garnished". 

If this all comes true, I would be so thrilled!! I know it's a lot of work, but super cool.

**Comment by MrRedstoneToGo** [comment]
How do you like that? Is this expected to be added or not? This would help me plan my (Create: Garnished based) modpack. Then I know whether I should think off new recipes with the new colors or not.

**Comment by DakotaPride** [comment]
I do not think that this will make it into the mod, though it is hard to say right now considering that I'm looking to rework Mastic Resin a little bit in the v1.8 update. Apologies for not responding, for some reason I didn't receive a notification regarding this.

**Comment by MrRedstoneToGo** [comment]
What if you add all the missing mastic resin colours? I mean some colour combinations in the current request won't work like purple and yellow.

I think you have to be very creative now when it comes to reacting with lava :)

**Comment by MrRedstoneToGo** [comment]
Have you received a notification that there is a new issue titled “Some QoL Ideas”?

**Comment by DakotaPride** [comment]
Yep! I'll take a look at it now!

**Comment by DakotaPride** [comment]
Hello! I recently made a post relating to this specific issue. Feel free to let me know your thoughts on it if you'd like! The changes listed would also not be in v1.8, but instead in a later version such as v1.9 or v2.0

https://create-garnished.github.io/blog/future_mastic_resin_rework.html

**Comment by MrRedstoneToGo** [comment]
Fluid Interaction with lava: Finde ich auch, die Fluid combinations mit lava waren ein bisschen overpowered. Wie wäre es mit Terracotta als Output?

**Comment by MrRedstoneToGo** [comment]
Fluid Interaction with lava: Finde ich auch, die Fluid combinations mit lava waren ein bisschen overpowered. Wie wäre es mit Terracotta als Output?

Inventory clutter: Look at glass, glass panes; wool, beds; concrete, concrete powder, terracotta, glazed terracotta; candles...

**Comment by MrRedstoneToGo** [comment]
**Fluid Interaction with lava:** I agree, the Fluid combinations with lava were a bit overpowered. How about terracotta as an output? If you add your own stone types, here are my suggestions. For all purple-like colors, I used unstable stone (gold and zinc) as a inspiration:
Iron: red, pink, black, gray
Gold: orange, brown, yellow, magenta
Copper: green, cyan, lime, light gray
Zinc: blue, light blue, white, purple

After all, you can argue about the distribution of colors, but this is my suggestion. 

**Inventory clutter:** Look at glass, glass panes; wool, beds; concrete, concrete powder, terracotta, glazed terracotta; candles...
And please DON'T ADD effects for different colour variants.

**Comment by DakotaPride** [comment]
Released! Let me know if you find any bugs or other stuff!

**Comment by MrRedstoneToGo** [comment]
Everything seems to work (I'm on vacation right now, so I can't test it in game). I just noticed that slime balls can now be made by bulk dyeing dough with LIME dye!
Another thing that would add much more depth to the whole dyeing fan thing is that shapeless recipes with only one dye and one item or a shaped recipe with a dye surrounded by items (= terracotta dyeing) automatically generate the respective bulk dyeing recipe! Just like packing recipes. All the other recipes (~compacting) are just additional.
