### ISSUE TITLE
Double ".json" ending

### ISSUE THREAD

**Issue by MrRedstoneToGo** [DakotaPride/create-garnished#58]
src/main/resources/data/garnished/recipes/freezing/minecraft/sugar_from_void_dust.json.json has in all branches a double ".json" ending. Simply rename them.

**Comment by MrRedstoneToGo** [comment]
Also take a look at how peanut oil is made in reality. The oil simply consists of pressed peanuts (heated compacting peanuts). This would make it possible to obtain lava in Skyblock, for example! So far salt is still the problem. However, if you want peanut oil to continue to be a late game resource, leave the recipe as is.

**Comment by DakotaPride** [comment]
I would rather Peanut Oil remain as is, though I do think that you can change the recipes/JSON functions using KubeJS for your modpack.

**Comment by MrRedstoneToGo** [comment]
Or a datapack. If cinder flour gets another recipe, maybe that would be possible with Craft Additions Biofuel. I'm excited...
