### ISSUE TITLE
Some QoL ideas

### ISSUE THREAD

**Issue by MrRedstoneToGo** [DakotaPride/create-garnished#59]
Over time I discovered some cool little features or ones that should have already existed.

1 Add effect descriptions:

![2024-04-08_19 58 06](https://github.com/DakotaPride/create-garnished/assets/163460667/0288f127-2c70-492b-8fc0-aacb1006a3e3)

2 Add a recipe type or a tooltip for items that can only be obtained through ravaging/salvaging enchantment

3 In the file (1.20.1) src/main/java/net/dakotapride/garnished/registry/GarnishedTabs.java aren't all items. Missing items:
EMPTY_CRIMSON_TUSK
SENILE_SPREAD
MOLTEN_REMNANT
MOLTEN_STEW
SOLEMN_DUST
PECAN_PIE_SLICE
PHANTOM_BURGER
PHANTOM_BEEF_PATTY
GLOW_INK_ROLL
GLOW_INK_ROLL_SLICE
(+ all INCOMLETE_... items but they aren't needed)
CHOC(H)OLATE_GLAZED_NUT_MIX has too many "H"s.

4 Add REI combat (check if senile spread is there)

9 Add brewing recipe for freezing potion

11 Modrinth logs show an error that
https://github.com/DakotaPride/create-garnished/blob/b66b2c04d9bd1ec5f0aebbec5b5eed3404f978c1/src/main/resources/data/garnished/recipes/integration/cooking/nut_nacho_bowl.json#L29-L31
is a tag and not an item, which is correct.

12 Polar Hide Scratch Paper does not work if the rose quartz is in the off hand and rose quartz on the floor disappears after polishing.

13 That must be c:dough: https://github.com/DakotaPride/create-garnished/blob/b66b2c04d9bd1ec5f0aebbec5b5eed3404f978c1/src/main/resources/data/garnished/recipes/deploying/sturdy_waffle.json#L5
But that should be the last Forge tag in the Fabric version.

**Comment by DakotaPride** [comment]
1. Will look further into it, however, my only concern with this is that it is only something that affects JEI, REI, or EMI instead of all of them. Could you provide the mod (if any, I'm not too familiar with EMI) that you used to have effect descriptions?
2. This is something that I tested with Create: BTTK (modpack) and do think that it would be beneficial. Though, again, would like it to be a feature across all versions and not just JEI or others.
3. It should already show up in JEI, what Garnished version are you on specifically?
4. Is this a continuation of 3? I'm not quite sure what you mean by "REI Combat," since, again, it should already show up in any item viewer.
5. I don't see this becoming a feature. While changing the current system would break a lot of contraptions and farms, the reason that I don't want to change it is because I believe that the current system already functions quite well. Maybe in the future, if I change my mind, this might be implemented, however.
6. Similar to 5.
7. Yes, Voltaic Seagrass is a building block that can be found in Cold Ocean biomes.
8. This is already something fixed internally, it simply has not been released yet.
9. There are already recipes for obtaining Freezing potions
<img width="763" alt="image" src="https://github.com/DakotaPride/create-garnished/assets/82760983/7da2c043-bb5e-444f-8c3d-a3d829a92f62">

10. I assume that's because of a check within the code to ensure that the player is eligible for damage. While the code is technically correct and shouldn't cause any issues. I might adjust this in v1.8, unsure though.
<img width="618" alt="image" src="https://github.com/DakotaPride/create-garnished/assets/82760983/7e51ee94-d6a3-47a0-85d1-451020522aa8">

**Comment by MrRedstoneToGo** [comment]
1. It is EMIffect, this was the only mod that specifies the translation path. Everyone else said “No description available.” Since "effect.garnish.aversion.description" doesn't contain "emiffect" or anything, I'm assuming this is vanilla (?) and should work for all mods. Just add a few entries to the language/translation file and check whether the tooltip also appears in JEED or effect description.
2. Maybe these tooltips like in Create where you press [Shift].
3. 1.7.5 It's interesting. After adding EMI combat, the senile spread suddenly disappeared.
4. Bulk Freezing and Bulk Dyeing, and check whether senile spread disappears.
3/4b. Solemn dust is missing too.
9. I tried both and they didn't work, even in the brewing stand
10. The Player is also immune to Powder Snow in Vanilla while wearing Leather Armor. I reported the bug and somebody told me, that his is intended, so nothing to change for you.

**Comment by MrRedstoneToGo** [comment]
1. [Test.zip](https://github.com/DakotaPride/create-garnished/files/14914624/Test.zip)
Load this ressourcepack. With this single entry in the language file all three mods are affected.

**Comment by MrRedstoneToGo** [comment]
1 It is EMIffect, this was the only mod that specifies the translation path. Everyone else said “No description available.” I also added a test description for aversion effect (example) via the resource pack [Test.zip](https://github.com/DakotaPride/create-garnished/files/14921572/Test.zip) and it worked with Effect Description and JEED too.

2 Maybe these tooltips like in Create where you press [Shift].

3 1.7.5 It's interesting. After adding EMI combat, the senile spread suddenly disappeared.

4 Bulk Freezing and Bulk Dyeing, and check whether senile spread disappears.

3/4b. Solemn dust is missing too.

9 I tried both and they didn't work, even in the brewing stand

10 The Player is also immune to Powder Snow in Vanilla while wearing Leather Armor. I reported the bug and somebody told me, that his is intended, so nothing to change for you.

**Comment by DakotaPride** [comment]
btw, what mod loader (I assume Fabric?) & MC version are you playing on? Just in case some of these are version-specific issues.

**Comment by MrRedstoneToGo** [comment]
Sie haben richtig angenommen und MC-Version 1.20.1

**Comment by MrRedstoneToGo** [comment]
11. Modrinth logs shows error, that 
https://github.com/DakotaPride/create-garnished/blob/b66b2c04d9bd1ec5f0aebbec5b5eed3404f978c1/src/main/resources/data/garnished/recipes/integration/cooking/nut_nacho_bowl.json#L29-L31
is a tag and no item, which is right

**Comment by MrRedstoneToGo** [comment]
You assumed correctly and Minecraft version 1.20.1

Also, there's a new but easy to fix bug (11)

**Comment by MrRedstoneToGo** [comment]
This time Phantom Patties are missing. Is there any technical similarity to Senile Spread, Solemn Dust and Phantom Patties?

**Comment by MrRedstoneToGo** [comment]
This time Phantom Patties are missing. Are there any technical similarities between Senile Spread, Solemn Dust and Phantom Patties? (+bug 12)

**Comment by DakotaPride** [comment]
None of them should have anything in common, no. Not sure why they would be missing to begin with, even if they did have something functionally similar. Did it disappear randomly or was it always not there?

**Comment by MrRedstoneToGo** [comment]
I think I have the reason now. In this file (1.20.1) src/main/java/net/dakotapride/garnished/registry/GarnishedTabs.java aren't all items. For example our three items are missing. Compare with the item registry class and check if every item is there.

**Comment by MrRedstoneToGo** [comment]
I think I have the reason now. In this file (1.20.1) src/main/java/net/dakotapride/garnished/registry/GarnishedTabs.java aren't all items. Missing items:
EMPTY_CRIMSON_TUSK
SENILE_SPREAD
MOLTEN_REMNANT
MOLTEN_STEW
SOLEMN_DUST
PECAN_PIE_SLICE
PHANTOM_BURGER
PHANTOM_BEEF_PATTY
GLOW_INK_ROLL
GLOW_INK_ROLL_SLICE
(+ all INCOMLETE_... items but they aren't needed)

CHOC(H)OLATE_GLAZED_NUT_MIX has too many "H"s.

btw you are always allowed to remove some issues in the first comment if you have fixed them, even if they are not in an official release.

**Comment by MrRedstoneToGo** [comment]
And this is c:dough

https://github.com/DakotaPride/create-garnished/blob/b66b2c04d9bd1ec5f0aebbec5b5eed3404f978c1/src/main/resources/data/garnished/recipes/deploying/sturdy_waffle.json#L5C15-L5C20

**Comment by MrRedstoneToGo** [comment]
And this is c:dough

https://github.com/DakotaPride/create-garnished/blob/b66b2c04d9bd1ec5f0aebbec5b5eed3404f978c1/src/main/resources/data/garnished/recipes/deploying/sturdy_waffle.json#L5C15-L5C20

**Comment by MrRedstoneToGo** [comment]
I updated 3 and added 13.

Übrigens, Du kannst auch Punkte oben löschen, wenn du sie erledigt hast, selbst wenn sie noch nicht in einem Release sind.

**Comment by MrRedstoneToGo** [comment]
I updated 3 and added 13.

By the way, you can also delete some things above once you have completed them, even if they are not yet in a release.

**Comment by DakotaPride** [comment]
I wanted to make sure that everything was fixed first before removing or closing the issue. Since I haven't gotten everything ported yet, still not sure if everything is gonna work alright.

**Comment by DakotaPride** [comment]
> 12 Polar Hide Scratch Paper does not work if the rose quartz is in the off hand and rose quartz on the floor disappears after polishing.

So, while testing, found out that this actually applies to **any** item. However, it should be a simple fix.

**Comment by DakotaPride** [comment]
btw, any integrated items (such as the phantom burger or pecan pie slice) aren't meant to show up in the Garnished-specific creative tabs, or they aren't intended to, at least.

**Comment by MrRedstoneToGo** [comment]
> > 12 Polar Hide Scratch Paper does not work if the rose quartz is in the off hand and rose quartz on the floor disappears after polishing.
> 
> So, while testing, found out that this actually applies to **any** item. However, it should be a simple fix.

I only took Rose Quartz as an example

> btw, any integrated items (such as the phantom burger or pecan pie slice) aren't meant to show up in the Garnished-specific creative tabs, or they aren't intended to, at least.

What about the Farmer's Delight creative tab (if you have access to it and Farmer's Delight is loaded)? The thing is that items that are not in any creative tab are not displayed in any recipe viewer.

**Comment by DakotaPride** [comment]
All of this should be fixed now, let me know if you come across anything else!
