### ISSUE TITLE
Nut Trees Won't Grow [Forge]

### ISSUE THREAD

**Issue by Ang3l404** [DakotaPride/create-garnished#6]
- The dedicated tree's won't grow at all in forge. There's also a slight issue with the tree's in that the leaves spawn too far from the wood when they're force grown (bonemealed) and end up not being in the harvest from chopping down a tree.

Personally, I think the old system of using crops is better than having to filter out tree loottables (regular saplings, wood, sticks and apples), just to get to the nuts.

**Comment by DakotaPride** [comment]
Could you replicate this issue and send a video/screenshots of it occurring? Testing this inside of a development environment works perfectly fine.

**Comment by DakotaPride** [comment]
This report has been marked as "inactive" as the issue doesn't seem to appear elsewhere and no follow-up to the previous statements have occurred. If you believe that this is in error, or now have important information regarding your issue, please put it here and let me know. Thank you for your understanding and apologies for the inconvenience! 

This issue will remain open until confirmation on the issue's status has been provided.
