### ISSUE TITLE
[Bug] Crash on startup

### ISSUE THREAD

**Issue by QianFuv** [DakotaPride/create-garnished#60]
After update CreateDreams&Desires mod from V0.2.5b to V0.1a(rewrite version)
Crash report: https://mclo.gs/fGCVBdQ

**Comment by QianFuv** [comment]
Disabling CreateDreams&Desires allows the game to start normally.

**Comment by DakotaPride** [comment]
The rewrite of Dreams & Desires may have caused this. Have you tried downgrading to a version prior to the rewrite just to make sure?

I'll see if there's anything that I can do on my end, though.

**Comment by DakotaPride** [comment]
First, have you tried downloading and installing the test build version available on the discord (v1.8, it's not the most recent version built, but it should allow proper testing)? Second, it seems that Dreams & Desires has had an update since this issue was created, could you try updating to that version and let me know if the issue persists?

**Comment by QianFuv** [comment]
Sorry for not replying in a timely manner. I have removed CreatDreams&Desires from my mod list, so I will not continue to track this issue. I'm sorry.

**Comment by DakotaPride** [comment]
Oh, okay then. Well, if you experience this issue in the future, let me know so that I can look into it!

**Comment by QianFuv** [comment]
Sure!

**Comment by DakotaPride** [comment]
Whilst you may not be experiencing the issue anymore, Luna (C:D&D developer) reached out regarding the issue and we are currently in the process of troubleshooting it! (concluded that it was probably an API issue)

**Comment by DakotaPride** [comment]
Should be fixed now! Feel free to reinstall Dreams & Desires if you'd like and let me know if there are any other issues!

**Comment by QianFuv** [comment]
That's great news! I'll give it a try right away!
