### ISSUE TITLE
Sturdy Waffle (and perhaps other items) use incorrect tags in crafting recipe on fabric.

### ISSUE THREAD

**Issue by NolanHewitt** [DakotaPride/create-garnished#61]
The recipe calls for forge:dough, I imagine a leftover from the forge version of the mod. I think the right tag would be c:dough?

**Comment by DakotaPride** [comment]
Ah, yes, apologies for this. This somehow slips through every single update with at least one of the recipes.

What MC version are you playing on, btw?

**Comment by NolanHewitt** [comment]
No worries, I can imagine keeping track of so many recipes for two different version would be a lot.

I’m on MC version 1.20.1

**Comment by DakotaPride** [comment]
Alright, it should be fixed when v1.8 releases - I'll make sure to let you know when it does!

**Comment by NolanHewitt** [comment]
Thank you, I appreciate it!

**Comment by DakotaPride** [comment]
Should be fixed now! Let me know if there are any other issues!
