### ISSUE TITLE
every 1.8 block that is transparent has a black texture

### ISSUE THREAD

**Issue by MrRedstoneToGo** [DakotaPride/create-garnished#62]
See there:
![2024-05-29_17 11 17](https://github.com/DakotaPride/create-garnished/assets/163460667/9d2caa20-d995-42b5-b4e6-ed620fbb42b1)

**Comment by MrRedstoneToGo** [comment]
And is there a way to get Sophistical Petals?

**Comment by DakotaPride** [comment]
> And is there a way to get Sophistical Petals?

Crushing or milling a Pansophical Daisy should work

**Comment by NolanHewitt** [comment]
![huge_2024-05-30_04 35 37](https://github.com/DakotaPride/create-garnished/assets/52480898/c865e596-2325-44a3-b5bf-11e22f35c50e)
Looks ok to me, maybe its a version specific bug?

**Comment by MrRedstoneToGo** [comment]
@NolanHewitt I am (always) playing on Fabric 1.20.1

> > And is there a way to get Sophistical Petals?
> 
> Crushing or milling a Pansophical Daisy should work

Where are the recipes?

**Comment by DakotaPride** [comment]
I was mistaken, it is just crushing Pansophical Daisies. However, it does also look like the recipe doesn't have the petals for some reason. Thank you for letting me know, the issue will be fixed in the next version!

**Comment by MrRedstoneToGo** [comment]
The only thing missing is this black texture on transparent blocks...

**Comment by DakotaPride** [comment]
> The only thing missing is this black texture on transparent blocks...

That'll also be fixed in the next version, apologies for the inconvenience!

**Comment by DakotaPride** [comment]
Should now be fixed!
