### ISSUE TITLE
Recipe that should be removed - or not?

### ISSUE THREAD

**Issue by MrRedstoneToGo** [DakotaPride/create-garnished#63]
In the create-garnished.github.io blog post: "Another change that is coming is related to Senile Spread - which will no longer be obtainable by simply applying a piece of Senile Dust to Bone meal."

The recipe still exists!

**Comment by MrRedstoneToGo** [comment]
Speaking of senile stuff: Irate Tusks have the same texture as normal Tusks only slightly lighter, is that right?

**Comment by DakotaPride** [comment]
> In the create-garnished.github.io blog post: "Another change that is coming is related to Senile Spread - which will no longer be obtainable by simply applying a piece of Senile Dust to Bone meal."
> 
> The recipe still exists!

I must've missed that somehow, thank you for letting me know!

> Speaking of senile stuff: Irate Tusks have the same texture as normal Tusks only slightly lighter, is that right?

Yep! It's meant to be somewhat hard to distinguish at first glance (of course, the name of the item gives it away instantly).

**Comment by DakotaPride** [comment]
I assume you're on Fabric 1.20.1?

**Comment by MrRedstoneToGo** [comment]
Yes as always

**Comment by DakotaPride** [comment]
Should now be fixed!
