### ISSUE TITLE
Some incorrect item names/tags in recipes...

### ISSUE THREAD

**Issue by MrRedstoneToGo** [DakotaPride/create-garnished#66]
1. https://github.com/DakotaPride/create-garnished/blob/adb326b538d501363bc4c3fe20a77ba43a1b7db5/src/main/resources/data/garnished/recipes/integration/cutting/senile_bone_from_tusk.json#L13: garnished:tusk, it's not vanilla.
2. https://github.com/DakotaPride/create-garnished/blob/adb326b538d501363bc4c3fe20a77ba43a1b7db5/src/main/resources/data/garnished/recipes/integration/cutting/senile_bone_from_irate_tusk.json#L13: also applies for irate tusks.
3. https://github.com/DakotaPride/create-garnished/blob/adb326b538d501363bc4c3fe20a77ba43a1b7db5/src/main/resources/data/garnished/recipes/integration/cooking/nut_nacho_bowl.json#L30: this is a tag, not an item.

4. Have a look at the logs, they are very useful to find out such small mistakes.

**Comment by DakotaPride** [comment]
That's all I did the week prior to releasing v1.8, and somehow these still slip through the cracks. I even remember fixing the c:cheese issue before, I must've accidentally rolled back the file at some point.

**Comment by MrRedstoneToGo** [comment]
I know you fixed the c:cheese problem, after all I brought it to your attention. I myself am a bit surprised that the bug still exists/exists again.

**Comment by DakotaPride** [comment]
Should be fixed now, I searched far and wide through the logs, there should be **no more** issues.
