### ISSUE TITLE
Questions about Antique Swath and Meat Scraps

### ISSUE THREAD

**Issue by MrRedstoneToGo** [DakotaPride/create-garnished#68]
Is there a way to obtain Antique Swath or are there any uses for Meat Scraps (not only consumption)?

Create: Garnished version: 187-1.20.1-fabric

**Comment by DakotaPride** [comment]
Antique Swathe can be obtained from Desert Pyramids and Meat Scraps (currently) don't have any other use than to be eaten. However, I do hope to eventually have an update that is village/raid-oriented, so perhaps it'll receive some more uses then.

**Comment by MrRedstoneToGo** [comment]
Thanks
