### ISSUE TITLE
Zultanite crushing

### ISSUE THREAD

**Issue by DadamaldaDad** [DakotaPride/create-garnished#71]
2 recipes regarding zultanite crushing have invalid items:

Iron from zultanite and gold from zultanite reference "create:iron_nugget" and "create:gold_nugget" respectively instead of using the "minecraft" namespace.

Would take too long to make a pull request for this mistake.

**Comment by DakotaPride** [comment]
May be marked as completed, but still waiting on Curseforge approval!

**Comment by DakotaPride** [comment]
Should now be available on Curseforge - uploading to Modrinth now!
