### ISSUE TITLE
Cannot create Liquefied Mastic Resin with Heated Mixer

### ISSUE THREAD

**Issue by cuppachino** [DakotaPride/create-garnished#73]
You cannot craft Liquefied Mastic Resin using a Heated Mixer, but JEI suggests you can. The mixer does not spin.

![image](https://github.com/user-attachments/assets/f1a43580-bcb6-4c86-be76-a882747f74cc)
![image](https://github.com/user-attachments/assets/f405dcd2-e797-41bf-8b74-a5e44b037d8a)

Is there another way you are meant to obtain the liquid?

Version: `garnished-2.0.1+1.19.2-forge`

**Comment by DakotaPride** [comment]
Is there any errors that pop up in the logs relating to the recipe itself?

**Comment by cuppachino** [comment]
> Is there any errors that pop up in the logs relating to the recipe itself?

These are the only errors related to garnished.

<details><summary>Log</summary>

```
14:03:16.373
net.minecraft.tags.TagLoader
Worker-ResourceReload-9
[Load My Fucking Tags] Couldn't load certain entries with the tag forge:affected_by/ravaging: minecraft:sniffer (from garnished-2.0.1+1.19.2-forge.jar)
14:03:17.801
net.minecraft.world.item.crafting.RecipeManager
Render thread
Parsing error loading recipe garnished:integration/cooking/galvanic_haunting: com.google.gson.JsonSyntaxException: Unknown item 'minecraft:lustrous_pearl'
14:03:18.135
net.minecraft.world.item.crafting.RecipeManager
Render thread
Parsing error loading recipe garnished:crushing/brittle_dust: com.google.gson.JsonSyntaxException: Missing type, expected to find a string
```
</details>

**Comment by DakotaPride** [comment]
Should now be fixed! Let me know if you come across any other issues!
