### ISSUE TITLE
[Bug] Spout Not Applying Honey to Nuts

### ISSUE THREAD

**Issue by Routhinator** [DakotaPride/create-garnished#74]
**Minecraft and Mod version** 🐞
Minecraft: 1.20.1
Mod Loader: Fabric 
Mod Version: 2.0.2

**Describe the bug** 🐞
When placing a nut on a depot below a spout filled with honey, nothing happens.

**To Reproduce** ⚙️

1. Setup a spout with a depot below it.
2. Pipe honey into the spout.
3. Place a nut on the depot and wait.
4. Nothing will occur.

**Expected behavior** ✔️
A honey coated nut item should be created.

**Screenshots** 📸
![2024-11-28_05 58 15](https://github.com/user-attachments/assets/0fbd6aa6-39c9-4781-b54e-5eb5fe874595)
![2024-11-28_05 58 30](https://github.com/user-attachments/assets/8fdceb64-f728-40e3-96cd-cacd61110c01)
![2024-11-28_05 58 35](https://github.com/user-attachments/assets/a133e772-c2ac-43c5-b315-f2cb05563737)
![2024-11-28_05 58 41](https://github.com/user-attachments/assets/a100879f-2922-4394-a24e-88b516e65632)

**Is the issue happening in combination with other mods? (If yes, please provide a full list)** 🧩
This is being experienced in the following experimental pack I am building, mod list is here.

https://modrinth.com/modpack/magpunkrpg/version/dRBdeba3

**Comment by DakotaPride** [comment]
Make sure the nuts are garnished before spouting honey onto them

**Comment by Routhinator** [comment]
OH.. that was subtle. I completely missed that subtext and just saw cashew - that's what I get for playtesting before I have my :coffee: 


Sorry about the time wasted here.
